package com.glutton.cms.mapping.category;

import com.glutton.cms.dao.category.Category;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_category
     *
     * @mbg.generated Fri Jul 26 16:12:54 CST 2019
     */
    int deleteByPrimaryKey(Long cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_category
     *
     * @mbg.generated Fri Jul 26 16:12:54 CST 2019
     */
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_category
     *
     * @mbg.generated Fri Jul 26 16:12:54 CST 2019
     */
    Category selectByPrimaryKey(Long cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_category
     *
     * @mbg.generated Fri Jul 26 16:12:54 CST 2019
     */
    List<Category> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_category
     *
     * @mbg.generated Fri Jul 26 16:12:54 CST 2019
     */
    int updateByPrimaryKey(Category record);

    List<Category> selectParentId(int pId);
}