package com.glutton.cms.mapping.person;

import com.glutton.cms.dao.person.CmsUser;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface CmsUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated Fri Jul 26 14:15:26 CST 2019
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated Fri Jul 26 14:15:26 CST 2019
     */
    int insert(CmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated Fri Jul 26 14:15:26 CST 2019
     */
    CmsUser selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated Fri Jul 26 14:15:26 CST 2019
     */
    List<CmsUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated Fri Jul 26 14:15:26 CST 2019
     */
    int updateByPrimaryKey(CmsUser record);
}