package com.glutton.cms.mapping.person;

import com.glutton.cms.dao.person.CmsUserAccount;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface CmsUserAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_account
     *
     * @mbg.generated Fri Jul 26 14:37:01 CST 2019
     */
    int deleteByPrimaryKey(Long accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_account
     *
     * @mbg.generated Fri Jul 26 14:37:01 CST 2019
     */
    int insert(CmsUserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_account
     *
     * @mbg.generated Fri Jul 26 14:37:01 CST 2019
     */
    CmsUserAccount selectByPrimaryKey(Long accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_account
     *
     * @mbg.generated Fri Jul 26 14:37:01 CST 2019
     */
    List<CmsUserAccount> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_account
     *
     * @mbg.generated Fri Jul 26 14:37:01 CST 2019
     */
    int updateByPrimaryKey(CmsUserAccount record);


    CmsUserAccount findAccount(CmsUserAccount record);
}