package com.glutton.cms.dao.category;

import java.util.Date;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_category.c_id
     *
     * @mbg.generated Fri Jul 26 16:12:54 CST 2019
     */
    private Long cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_category.parent_id
     *
     * @mbg.generated Fri Jul 26 16:12:54 CST 2019
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_category.c_name
     *
     * @mbg.generated Fri Jul 26 16:12:54 CST 2019
     */
    private String cName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_category.c_create_time
     *
     * @mbg.generated Fri Jul 26 16:12:54 CST 2019
     */
    private Date cCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_category.c_order
     *
     * @mbg.generated Fri Jul 26 16:12:54 CST 2019
     */
    private Long cOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_category.c_aliase
     *
     * @mbg.generated Fri Jul 26 16:12:54 CST 2019
     */
    private String cAliase;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_category.c_id
     *
     * @return the value of cms_category.c_id
     *
     * @mbg.generated Fri Jul 26 16:12:54 CST 2019
     */
    public Long getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_category.c_id
     *
     * @param cId the value for cms_category.c_id
     *
     * @mbg.generated Fri Jul 26 16:12:54 CST 2019
     */
    public void setcId(Long cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_category.parent_id
     *
     * @return the value of cms_category.parent_id
     *
     * @mbg.generated Fri Jul 26 16:12:54 CST 2019
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_category.parent_id
     *
     * @param parentId the value for cms_category.parent_id
     *
     * @mbg.generated Fri Jul 26 16:12:54 CST 2019
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_category.c_name
     *
     * @return the value of cms_category.c_name
     *
     * @mbg.generated Fri Jul 26 16:12:54 CST 2019
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_category.c_name
     *
     * @param cName the value for cms_category.c_name
     *
     * @mbg.generated Fri Jul 26 16:12:54 CST 2019
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_category.c_create_time
     *
     * @return the value of cms_category.c_create_time
     *
     * @mbg.generated Fri Jul 26 16:12:54 CST 2019
     */
    public Date getcCreateTime() {
        return cCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_category.c_create_time
     *
     * @param cCreateTime the value for cms_category.c_create_time
     *
     * @mbg.generated Fri Jul 26 16:12:54 CST 2019
     */
    public void setcCreateTime(Date cCreateTime) {
        this.cCreateTime = cCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_category.c_order
     *
     * @return the value of cms_category.c_order
     *
     * @mbg.generated Fri Jul 26 16:12:54 CST 2019
     */
    public Long getcOrder() {
        return cOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_category.c_order
     *
     * @param cOrder the value for cms_category.c_order
     *
     * @mbg.generated Fri Jul 26 16:12:54 CST 2019
     */
    public void setcOrder(Long cOrder) {
        this.cOrder = cOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_category.c_aliase
     *
     * @return the value of cms_category.c_aliase
     *
     * @mbg.generated Fri Jul 26 16:12:54 CST 2019
     */
    public String getcAliase() {
        return cAliase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_category.c_aliase
     *
     * @param cAliase the value for cms_category.c_aliase
     *
     * @mbg.generated Fri Jul 26 16:12:54 CST 2019
     */
    public void setcAliase(String cAliase) {
        this.cAliase = cAliase == null ? null : cAliase.trim();
    }
}