package com.glutton.cms.dao.person;

import java.util.Date;

public class CmsUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user.user_id
     *
     * @mbg.generated Fri Jul 26 16:29:37 CST 2019
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user.user_name
     *
     * @mbg.generated Fri Jul 26 16:29:37 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user.user_age
     *
     * @mbg.generated Fri Jul 26 16:29:37 CST 2019
     */
    private Integer userAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user.user_nickname
     *
     * @mbg.generated Fri Jul 26 16:29:37 CST 2019
     */
    private String userNickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user.user_phone
     *
     * @mbg.generated Fri Jul 26 16:29:37 CST 2019
     */
    private String userPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user.join_date
     *
     * @mbg.generated Fri Jul 26 16:29:37 CST 2019
     */
    private Date joinDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user.user_email
     *
     * @mbg.generated Fri Jul 26 16:29:37 CST 2019
     */
    private String userEmail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user.user_id
     *
     * @return the value of cms_user.user_id
     *
     * @mbg.generated Fri Jul 26 16:29:37 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user.user_id
     *
     * @param userId the value for cms_user.user_id
     *
     * @mbg.generated Fri Jul 26 16:29:37 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user.user_name
     *
     * @return the value of cms_user.user_name
     *
     * @mbg.generated Fri Jul 26 16:29:37 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user.user_name
     *
     * @param userName the value for cms_user.user_name
     *
     * @mbg.generated Fri Jul 26 16:29:37 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user.user_age
     *
     * @return the value of cms_user.user_age
     *
     * @mbg.generated Fri Jul 26 16:29:37 CST 2019
     */
    public Integer getUserAge() {
        return userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user.user_age
     *
     * @param userAge the value for cms_user.user_age
     *
     * @mbg.generated Fri Jul 26 16:29:37 CST 2019
     */
    public void setUserAge(Integer userAge) {
        this.userAge = userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user.user_nickname
     *
     * @return the value of cms_user.user_nickname
     *
     * @mbg.generated Fri Jul 26 16:29:37 CST 2019
     */
    public String getUserNickname() {
        return userNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user.user_nickname
     *
     * @param userNickname the value for cms_user.user_nickname
     *
     * @mbg.generated Fri Jul 26 16:29:37 CST 2019
     */
    public void setUserNickname(String userNickname) {
        this.userNickname = userNickname == null ? null : userNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user.user_phone
     *
     * @return the value of cms_user.user_phone
     *
     * @mbg.generated Fri Jul 26 16:29:37 CST 2019
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user.user_phone
     *
     * @param userPhone the value for cms_user.user_phone
     *
     * @mbg.generated Fri Jul 26 16:29:37 CST 2019
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user.join_date
     *
     * @return the value of cms_user.join_date
     *
     * @mbg.generated Fri Jul 26 16:29:37 CST 2019
     */
    public Date getJoinDate() {
        return joinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user.join_date
     *
     * @param joinDate the value for cms_user.join_date
     *
     * @mbg.generated Fri Jul 26 16:29:37 CST 2019
     */
    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user.user_email
     *
     * @return the value of cms_user.user_email
     *
     * @mbg.generated Fri Jul 26 16:29:37 CST 2019
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user.user_email
     *
     * @param userEmail the value for cms_user.user_email
     *
     * @mbg.generated Fri Jul 26 16:29:37 CST 2019
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }
}